### ISSUE TITLE
 Alliance Bernstein is no longer accepting applications.

### ISSUE THREAD

**Issue by ankitprahladsoni** [christine-hu/summer-2019-internships#39]

**Comment by christine-hu** [comment]
Hey, thanks for opening the issue! The application seems to be open through this link: https://alliancebernstein.gr8people.com/index.gp?method=cappportal.showJob&layoutid=2092&inp1541=&inp1375=9947&opportunityid=9947 

Let me know if I’m mistaken!

**Comment by ankitprahladsoni** [comment]
oh, well, in that case, please update the link. The previous link directed to a closed opportunity.

**Comment by christine-hu** [comment]
Thanks for letting me know!
