### ISSUE TITLE
if i have different open positions for interns - what i should do? 

### ISSUE THREAD

**Issue by atherdon** [christine-hu/summer-2019-internships#65]
Am I qualified or this list have some strict approval process?

**Comment by ATecha** [comment]
As far as I know, there's no approval process. Just edit and submit a pull request like any other update.
I'm not the one who maintains the list or approves requests, so my 2 cents on that isn't the final word.

**Comment by christine-hu** [comment]
Sorry for the late response, but @ATecha is right, simply open a pull request and make any additions you would like!
